### ISSUE TITLE
Code is not working with multiple lines using STRING or ENTER

### ISSUE THREAD

**Issue by dslrcnc** [adafruit/Adafruit_CircuitPython_Ducky#5]
I keep receiving this message in the console:

`ValueError: No keycode available for character '\r' (13/0x0d).`

After executing this ducky script file
```
DELAY 1000
GUI r
ENTER
STRING 123
```
It seems the code reads the lines with an extra \r\n in the line 148, the code tries to remove \n but maybe it needs to remove also \r but this affects also the last line of the ducky script because it reads the line with 2 less caracters because the last line doesn't have the extra \r\n.

**Comment by dslrcnc** [comment]
Changing line 148 to:
`self.lines.append(line[:-2])`
and adding and extra ENTER into the last line of the duckyscript.txt file seems to work fine.
also the library could be fixed using rstrip() function to remove \r\n

**Comment by ladyada** [comment]
hiya good idea, please submit a PR to add `rstrip()`!

**Comment by Crims-on** [comment]
I'm running into the same issue when running the script, so please fix it
