### ISSUE TITLE
Custom keyboard layout

### ISSUE THREAD

**Issue by Crims-on** [adafruit/Adafruit_CircuitPython_Ducky#6]
How can I make a custom keyboard layout for this?

And also would it be possible to have two ducky scripts who execute depending on button press?

**Comment by tekktrik** [comment]
If you're looking for help using this library, please use the [Adafruit Forums](https://forums.adafruit.com/) or the Adafruit Discord server, since we only use issues to track problems and enhancements for libraries.  Thanks!

**Comment by Neradoc** [comment]
To be complete, the Ducky class takes a keyboard and keyboard layout as arguments:
https://docs.circuitpython.org/projects/ducky/en/latest/api.html#adafruit_ducky.Ducky

You can find (and request) international keyboards here:
https://github.com/Neradoc/Circuitpython_Keyboard_Layouts
